# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: hello.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'hello.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bhello.proto\x12\x0chelloPackage\"\x19\n\nAgeRequest\x12\x0b\n\x03\x61ge\x18\x01 \x01(\x05\"\x1d\n\x0b\x41geResponse\x12\x0e\n\x06\x61nswer\x18\x01 \x01(\t\"\x1c\n\x0cHelloRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x1d\n\rHelloResponse\x12\x0c\n\x04name\x18\x01 \x01(\t2\x8a\x01\n\nHelloWorld\x12@\n\x05hello\x12\x1a.helloPackage.HelloRequest\x1a\x1b.helloPackage.HelloResponse\x12:\n\x03\x61ge\x12\x18.helloPackage.AgeRequest\x1a\x19.helloPackage.AgeResponseB\rZ\x0bgrpc/golangb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'hello_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\013grpc/golang'
  _globals['_AGEREQUEST']._serialized_start=29
  _globals['_AGEREQUEST']._serialized_end=54
  _globals['_AGERESPONSE']._serialized_start=56
  _globals['_AGERESPONSE']._serialized_end=85
  _globals['_HELLOREQUEST']._serialized_start=87
  _globals['_HELLOREQUEST']._serialized_end=115
  _globals['_HELLORESPONSE']._serialized_start=117
  _globals['_HELLORESPONSE']._serialized_end=146
  _globals['_HELLOWORLD']._serialized_start=149
  _globals['_HELLOWORLD']._serialized_end=287
# @@protoc_insertion_point(module_scope)
